# PostgreSQL. Versions 8.2 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On OS X with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On OS X with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
local_postgresql: &local_postgresql
  username: postgres
  password: postgres
  encoding: unicode
  host: localhost

development: &default
  adapter: postgresql
  <<: *local_postgresql
  database: whatconference_development
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5

test:
  adapter: postgresql
  <<: *local_postgresql
  host: localhost
  database: whatconference_test
  encoding: unicode

production:
  adapter: pg
  database: db/production.pg
  pool: 5
  timeout: 5000
